name: hsp90-smfret-model
channels:
  - conda-forge
  - bioconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcblas=3.11.0=5_h0358290_openblas
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_16
  - libuuid=2.41.2=h5347b49_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - numpy-typing-compat=20250818.2.3=pyh5fd51be_0
  - openssl=3.6.0=h26f9b46_0
  - optype=0.15.0=pyhcf101f3_0
  - optype-numpy=0.15.0=pyh272cbef_0
  - pandas-stubs=2.3.3.251201=pyhd8ed1ab_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=hd63d673_1_cpython
  - python_abi=3.12=8_cp312
  - readline=8.3=h853b02a_0
  - scipy-stubs=1.16.3.3=pyhcf101f3_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - types-pytz=2025.2.0.20251108=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - blosc2==3.11.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - dill==0.4.0
      - fonttools==4.60.1
      - idna==3.11
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.45.1
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - msgpack==1.1.2
      - multiprocess==0.70.18
      - ndindex==1.10.0
      - numba==0.62.1
      - numexpr==2.14.1
      - numpy==2.3.4
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - platformdirs==4.5.0
      - py-cpuinfo==9.0.0
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - rich==14.2.0
      - salib==1.5.2
      - scipy==1.16.3
      - six==1.17.0
      - tables==3.10.2
      - tzdata==2025.2
      - urllib3==2.5.0
prefix: /home/abhinav/miniconda3/envs/hsp90-smfret-model
